### ISSUE TITLE
How do you find the commands defined in `commands.json`? 

### ISSUE THREAD

**Issue by JGuillaumin** [vinzeebreak/ironcar#2]
I would like to know how do you find the commands defined in the `json` file.
The Adafruit controller can receive 16-bit messages (integers in `[0, 4095]`). 
For exmples, these values can be sent to the steering motor : "left": 310, "right": 490.

But some messages are not interpreted by the gas or the steering motor. 
For example, if I send `0` to the steering, nothing happens. 
How can I find the complete dictionary `{'value:action'}` ? (where value is in  `[0, 4095]`) 

My goal, find a finer set of commands for gas and steering!

**Comment by srdadian** [comment]
Hi!
The (annoying) thing is that those numbers depend on your servos/car/ESC... 
If you're lucky, the info regarding your car might be online! 
We did not find ours :( So there might be a more elegant way to do it but we just wrote a simple script to try out values and saved the ones that looked best. This is why we stored it in a json so it's easy to change! 
Hope this helps :)
