### ISSUE TITLE
Launching ironcar_master.py - Does not find module named socketIO_client

### ISSUE THREAD

**Issue by Shenandohadom** [vinzeebreak/ironcar#3]
Hello,
After running ./install.sh and launching node car_server.js with no problem, I have the following error message when I run python ironcar_master.py:

ImportError : No module named socketIO_client

It is true that I cannot find any py file with such name.
Did I do something wrong?
Thank you.

**Comment by srdadian** [comment]
Hi! 
If everything went well for install.sh, it should have installed the raspi requirements and socketIO_client is in it. But you said you did not see any error for the install? 
Also we install everything on python3, and you said you launched with « python », which python is it linked to? 
Have you tried python3 ironcar_master.py?

**Comment by Shenandohadom** [comment]
Hi there,

When I run the install script the only red error message I have is the following:

tensorflow-1.1.0-cp34-cp34m-linux_armv71.whl is not a supported wheel on this platform

When I try python3 ironcar_master.py, it fails further on:

numpy.core.multiarray failed to import

The strange thing is that it was looking in 
/usr/local/lib/python3.5/dist-packages/scipy/linalg/blas.py

instead of looking into a directory with python3

Well I think I'll have to give up with the installation and this nice Ironcar idea... unless someone can help me debug that script....

**Comment by xbraininc** [comment]
Hello,
Could you try this command "sudo pip3 install -r requirements_raspi.txt" from the ironcar folder.
And paste this output here ?
pip3 is just a link to the python 3 version installed (python3.5 in your case), so quite normal it gives you this path.

**Comment by xbraininc** [comment]
Sorry about that, the install.sh is for python3.4 regarding the tensorflow installation.
Could you please replace line 20 and 21 with those ones : 
wget https://github.com/lhelontra/tensorflow-on-arm/releases/download/v1.4.0/tensorflow-1.4.0-cp35-none-linux_armv7l.whl
sudo pip3 install tensorflow-1.4.0-cp35-none-linux_armv7l.whl
And then paste again the output of the install.sh execution
Thanks

**Comment by Shenandohadom** [comment]
Hello and thank you for your help.

Here is what I get after what you proposed (I had to add "/tag/" in the path for the whl file) when I run "sudo pip3 install -r requirements_raspi.txt":

pi@raspberrypi:~/ironcar $ sudo pip3 install -r requirements_raspi.txt
Requirement already satisfied: numpy in /usr/lib/python3/dist-packages (from -r requirements_raspi.txt (line 1))
Requirement already satisfied: socketIO-client==0.7.2 in /usr/local/lib/python3.5/dist-packages (from -r requirements_raspi.txt (line 2))
Requirement already satisfied: Adafruit_PCA9685 in /usr/local/lib/python3.5/dist-packages (from -r requirements_raspi.txt (line 3))
Requirement already satisfied: Adafruit_BNO055 in /usr/local/lib/python3.5/dist-packages (from -r requirements_raspi.txt (line 4))
Requirement already satisfied: picamera in /usr/lib/python3/dist-packages (from -r requirements_raspi.txt (line 5))
Requirement already satisfied: keras==1.2.0 in /usr/local/lib/python3.5/dist-packages (from -r requirements_raspi.txt (line 6))
Requirement already satisfied: h5py==2.7.0 in /usr/local/lib/python3.5/dist-packages (from -r requirements_raspi.txt (line 8))
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from socketIO-client==0.7.2->-r requirements_raspi.txt (line 2))
Requirement already satisfied: websocket-client in /usr/local/lib/python3.5/dist-packages (from socketIO-client==0.7.2->-r requirements_raspi.txt (line 2))
Requirement already satisfied: requests>=2.7.0 in /usr/lib/python3/dist-packages (from socketIO-client==0.7.2->-r requirements_raspi.txt (line 2))
Requirement already satisfied: Adafruit-GPIO>=0.6.5 in /usr/local/lib/python3.5/dist-packages (from Adafruit_PCA9685->-r requirements_raspi.txt (line 3))
Requirement already satisfied: pyserial in /usr/lib/python3/dist-packages (from Adafruit_BNO055->-r requirements_raspi.txt (line 4))
Requirement already satisfied: pyyaml in /usr/local/lib/python3.5/dist-packages (from keras==1.2.0->-r requirements_raspi.txt (line 6))
Requirement already satisfied: theano in /usr/local/lib/python3.5/dist-packages (from keras==1.2.0->-r requirements_raspi.txt (line 6))
Requirement already satisfied: spidev in /usr/lib/python3/dist-packages (from Adafruit-GPIO>=0.6.5->Adafruit_PCA9685->-r requirements_raspi.txt (line 3))
Requirement already satisfied: adafruit-pureio in /usr/local/lib/python3.5/dist-packages (from Adafruit-GPIO>=0.6.5->Adafruit_PCA9685->-r requirements_raspi.txt (line 3))
Requirement already satisfied: scipy>=0.14 in /usr/local/lib/python3.5/dist-packages (from theano->keras==1.2.0->-r requirements_raspi.txt (line 6))

**Comment by Shenandohadom** [comment]
and when I run "python3.5 ironcar_master.py" here is the error message I get:

pi@raspberrypi:~/ironcar $ python3.5 ironcar_master.py
RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa
Traceback (most recent call last):
  File "ironcar_master.py", line 5, in <module>
    import scipy.misc
  File "/usr/local/lib/python3.5/dist-packages/scipy/misc/__init__.py", line 67, in <module>
    from scipy.interpolate._pade import pade as _pade
  File "/usr/local/lib/python3.5/dist-packages/scipy/interpolate/__init__.py", line 175, in <module>
    from .interpolate import *
  File "/usr/local/lib/python3.5/dist-packages/scipy/interpolate/interpolate.py", line 20, in <module>
    import scipy.linalg
  File "/usr/local/lib/python3.5/dist-packages/scipy/linalg/__init__.py", line 186, in <module>
    from .misc import *
  File "/usr/local/lib/python3.5/dist-packages/scipy/linalg/misc.py", line 5, in <module>
    from .blas import get_blas_funcs
  File "/usr/local/lib/python3.5/dist-packages/scipy/linalg/blas.py", line 196, in <module>
    from scipy.linalg import _fblas
ImportError: numpy.core.multiarray failed to import

**Comment by Shenandohadom** [comment]
To be very honest, I had the following error messages (in red) when I launched the modified install.sh script:

Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 353, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python3/dist-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "/usr/lib/python3/dist-packages/pip/download.py", line 809, in unpack_url
    unpack_file_url(link, location, download_dir, hashes=hashes)
  File "/usr/lib/python3/dist-packages/pip/download.py", line 715, in unpack_file_url
    unpack_file(from_path, location, content_type, link)
  File "/usr/lib/python3/dist-packages/pip/utils/__init__.py", line 617, in unpack_file
    flatten=not filename.endswith('.whl')
  File "/usr/lib/python3/dist-packages/pip/utils/__init__.py", line 502, in unzip_file
    zip = zipfile.ZipFile(zipfp, allowZip64=True)
  File "/usr/lib/python3.5/zipfile.py", line 1026, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.5/zipfile.py", line 1094, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
npm WARN ironcar_node@0.0.0 No repository field.

**Comment by Shenandohadom** [comment]
Thank you again for your help...

**Comment by vinzeebreak** [comment]
Did you try the newest version of `install.sh` ? It works on my raspi and I think we have the same version (of November 2017) of pi with Python 3.5.3 installed.
