### ISSUE TITLE
numpy does not import

### ISSUE THREAD

**Issue by Shenandohadom** [vinzeebreak/ironcar#4]
Hello,

Unfortunately the installation does not work well apparently, since launching python3.5 ironcar_master.py gives the following error message:

File "/usr/local/lib/python3.5/dist-packages/scipy/linalg/blas.py", line 196, in 
from scipy.linalg import _fblas
ImportError: numpy.core.multiarray failed to import

It looks like numpy modules are not found.

Could you help?
Many thanks!
Dominique

**Comment by Shenandohadom** [comment]
OK it's solved, if anyone has such a problem please contact me.

**Comment by vinzeebreak** [comment]
It can happen when an older version of numpy is installed on the rasberry pi and tensorflow needs a more recent version.  
How did you solve it ?

**Comment by vinzeebreak** [comment]
Ok. The solution consisted in installing a newer `numpy` version. For Python35, `numpy 1.14.0` seems to do the trick.  
I will make a 'requirements' file for different versions of python and update the `install.sh` file.
